### ISSUE TITLE
Zvt Checksum

### ISSUE THREAD

**Issue by tinohager** [StephenCleary/HashAlgorithms#1]
Hi, i try currently to calculate the zvt protocol checksum. In the documentation i found the info the checksum is `CRC-XModem` but i found no config that work. I also try ` public static Definition XModem` but i think the TruncatedPolynomial is invalid.
Do you have any idea what the problem is? I would like to build the checksum calculation on a tested library.

    Source: https://www.terminalhersteller.de/downloads/PA00P016_04_en.pdf -> 3.3 CRC-Calculation
    The CRC-checksum is calculated using the CRC-XModem with polynomial x16+ x15+ x10+ x3.
    All characters from the APDU plus ETX are used in the checksum calculation (see chapter Block-Structure)

This is my unittest

```cs
var data = new byte[] { 0x06, 0x00, 0x04, 0x00, 0x00, 0x00, 0x30, 0x03 };

var crc16 = new CRC16(new CRC16.Definition
{
	 TruncatedPolynomial = 0x1189
});
var crc16Checksum = crc16.ComputeHash(data);

var expected = new byte[] { 0x24, 0x89 };
Assert.IsTrue(expected.SequenceEqual(crc16Checksum));
```

This very simple logic gives the correct result

```cs
public static class CRCChecksum
{
    /// <summary>
    /// Returns [Lowbyte][highbyte]
    /// </summary>
    /// <param name="data"></param>
    /// <returns></returns>
    public static byte[] CalculateCRCBytes(byte[] data)
    {
        ushort crc = CalculateCRC(data);

        return BitConverter.GetBytes(crc);
    }

    public static ushort CalculateCRC(byte[] data)
    {
        ushort crc = 0;

        foreach (byte b in data)
            CRC(b, ref crc);

        return crc;
    }

    private static void CRC(byte b, ref ushort crc)
    {
        byte c1 = 0;
        for (int i = 0; i < 8; i++, b >>= 1)
        {
            c1 = (byte)(b ^ (byte)crc);
            crc >>= 1;
            if ((c1 & 1) != 0)
                crc ^= 0x8408;
        }
    }
}
```

**Comment by StephenCleary** [comment]
We're you able to find a solution for this?

**Comment by tinohager** [comment]
For the communication over the network no checksum is needed and I have currently no terminal over a serial connection so I can not ensure that the calculation is correct...

**Comment by StephenCleary** [comment]
I'm just wondering why you closed this issue?

**Comment by StephenCleary** [comment]
`0x1189` is `x^16 + x^12 + x^8 + x^7 + x^3 + x^0`, I believe.
`x^16 + x^15 + x^10 + x^3` would be `0x8408`.

When I have time, I'll do a test with that poly against [this implementation](https://github.com/prosoftgmbh/zvt/blob/master/zvt/Program.cs) and see if I can get a match.

**Comment by StephenCleary** [comment]
Got it. The documentation is actually wrong. It's not the CRC16 that is used in XModem. It's the CRC16 that is used in Kermit. These two are [very similar](https://reveng.sourceforge.io/crc-catalogue/16.htm#crc.cat.crc-16-kermit) and often confused.

This will get you what you need:

```C#
var crc16 = new CRC16(CRC16.Definition.Ccitt);
var crc16Checksum = calculator.ComputeHash(data);
```

**Comment by tinohager** [comment]
Thank you for the review, I will pass the information on like this
